name: Run Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar Cypress com a ação oficial
        uses: cypress-io/github-action@v6
