name: Run Cypress Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Instalar Cypress
        run: npx cypress install

      - name: Rodar os testes
        run: npx cypress run
